### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by gbrivady** [iScsc/wiresmash#12]
Check with the tools/libraries we are using; and pick a license for the project

**Comment by amtoine** [comment]
> Check with the tools/libraries we are using; and pick a license for the project
>
is there something more than the SFML library?

if not, simply check the license of this

but even so, we are only using the API of the SFML, not building upon or modifying its source code :thinking: 
i think we can pick the license we want

### i will personnally advocate for the GPL v3 :+1:

**Comment by gbrivady** [comment]
> i think we can pick the license we want

Probably yes, but better safe than sorry 👀 
I will have a deeper look at it soon

**Comment by amtoine** [comment]
> Probably yes, but better safe than sorry
> 
oh yes :+1: 

> I will have a deeper look at it soon
>
you can open a PR directly once you find out :+1:

**Comment by amtoine** [comment]
and in the end, if the SFML demands to have a specific license when using the API, this repo is not right at all, not having a LICENSE... :eyes:

**Comment by ctmbl** [comment]
@gbrivady did you manage to find some time to deal with it? 
There is too many Issues worked on at the time I'm trying to find the one that can be closed quickly ahah

**Comment by gbrivady** [comment]
Checked the SMFL stuff, we can just go with GPL v3 as per @amtoine suggestion. Will add a `LICENSE.md` for this asap
