### ISSUE TITLE
Improve readme: ToC, build requirements, wiki links, contributing

### ISSUE THREAD

**Issue by gbrivady** [iScsc/wiresmash#13]
Per a suggestion of @ctmbl in #7:

>simple Table of Content and placing incoming functionalities at the end

Other stuff that would be nice to add:

- proper version requirements for CMake and the SFML library
- link the wiki
- link `CONTRIBUTING.md` when we add one

If you have any other ideas, throw them here

**Comment by amtoine** [comment]
would you like to do that @gbrivady? :yum:

**Comment by gbrivady** [comment]
> would you like to do that @gbrivady? 😋

Yes I will probably end up doing it so I'm assigning myself

**Comment by amtoine** [comment]
cool thanks :ok_hand:
