### ISSUE TITLE
Define workflow for the project

### ISSUE THREAD

**Issue by gbrivady** [iScsc/wiresmash#15]
>> I can also think of adding the: fork, branch, commit, push, PR workflow (described as GitHub Flow in the website wiki) but maybe that will go in the CONTRIBUTING.md, other thing: when and how to add unit tests (but waybe wait for #6 )
>
>Did not think about that! Will steal the workflow from iscsc to create the `CONTRIBUTING.md`; but after #2.

_Originally posted by @gbrivady in https://github.com/iScsc/wiresmash/issues/10#issuecomment-1338154465_

Do this; see [the iscsc.fr wiki](https://github.com/iScsc/iscsc.fr/wiki/First-steps-and-resources) for more information, and the original comment for how to split information between the wiki and the markdown file.

**Comment by amtoine** [comment]
for now, at least the most important is already set up:
- the `main` branch is protected, we can not push onto it and need to go through a reviewing process with 2 approvals that can not be bypassed by anyone 

## the next things to address
- [ ] branch names
- [ ] commit conventions: _pre-commit / pre-push hooks?_
- [ ] CI pipelines: _pre-commit / pre-push hooks?_
  - [ ] #14
  - [ ] #6
