### ISSUE TITLE
Add namespaces to the codebase

### ISSUE THREAD

**Issue by gbrivady** [iScsc/wiresmash#20]
Meta-issue to keep track of everything that is not in a namespace.

Namespaces are intended to solve name conflicts between libraries, so to follow most `C++` projects, we should only use **two namespaces**: one for the engine, and one for the game; **no nested namespace**, except for specific stuff (also exist in the standard library, see `std::this_thread`).

If you feel like a nested namespace is required, feel free to use the `C++17` way of doing things, i.e. `namespace A::B { ... }` instead of `namespace A { namespace B { ... } }`.

- [x] engine:  `namespace engine` #24 
  - [ ] `box` system
  - [ ] `physics` system
  - [ ] `input` system
- [ ] game: `namespace game` OR `namespace wiresmash` OR an abreviation of Wiresmash would be nice EDIT: #27
  - [ ] `entity` system
    - [ ] as an exception, the `dev` subsystem may be double-nested
- [ ] settings: will probably end up as a subsystem of wiresmash, so namespace as above for now.

Side note: since adding namespaces "breaks" the code, we should probably keep the out of standard workflow, i.e. before/after we start work on a version.

**Comment by gbrivady** [comment]
If you have any idea of what may be a good abreviation for the `wiresmash` namespace, feel free to suggest them here.

**Comment by HumaNOOO** [comment]
I think wsm/wsmh would be cool and logical.
