### ISSUE TITLE
100% CPU usage when paused

### ISSUE THREAD

**Issue by anima-libera** [iScsc/wiresmash#22]
When the window looses focus (current implementation of pausing the game, it might change, see #18), [`sf::poolEvent`](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Window.php#a338e996585faf82e93069858e3b531b7) is called in a loop with no blocking or sleeping ([here](https://github.com/iScsc/wiresmash/blob/5c4b9ff64712e7aacba4e66d7bfc2b35a2a48c58/src/main.cpp#L44)) thus causing one CPU thread to always be at 100% usage until the window regains focus. This is not redundant with #18 (as #18 is not about the behavior/implementation of pausing). 

Using [`sf::waitEvent`](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Window.php#aaf02ab64fbc1d374eef3696df54137bc) instead blocks until events are received, which may be more suitable for this loop (I tried and it does not use 100% of a CPU core when out-of-focus anymore with the suggested change).

**Comment by amtoine** [comment]
that is a very good catch, thanks a lot :+1: 

i'm able to reproduce the exact same behaviour on my side.

**Comment by anima-libera** [comment]
^^
