### ISSUE TITLE
Look into Github Actions for CMake projects

### ISSUE THREAD

**Issue by gbrivady** [iScsc/wiresmash#6]
Github has a suggested action about CMake projects, so it would be nice if someone could look into how to setup it, what can be done with it, how it can help the project...

I think having an auto-build executable available to download  after each new release would be nice for example, but maybe we can do more fancy stuff, such as auto checking tests (if we write tests...) to help have faster PR, etc...

**Comment by ctmbl** [comment]
I think I'd be quite interested and appropriate for the job but I must warn you that I have other important things going on... 
So I can't give you any deadline, I'd prefer to be the plan B if someone else can find some time in the coming days/weeks :+1:

**Comment by amtoine** [comment]
@ctmbl

if you do not have the time, i think i can take this :+1: 
it's just a simple `.github/workflows/build.yml` that we need to write :yum: 

if that's fine with you, feel free to assign this to me :ok_hand:

**Comment by amtoine** [comment]
or we can wait 'til you have some time, if you want to build the pipeline yoursefl, i'll be happy to review what you've done :relieved: :wink:

**Comment by gbrivady** [comment]
If you are both fine with it, I will assign it to @amtoine for now, so we can see what is possible/if we need to make adjustements to the CMake files/etc.. , and then @ctmbl can pick it up if he wishes to do so when he has more time?

**Comment by ctmbl** [comment]
yes @amtoine @gbrivady go ahead!

**Comment by amtoine** [comment]
got it :ok_hand:
