### ISSUE TITLE
Project labels

### ISSUE THREAD

**Issue by gbrivady** [iScsc/wiresmash#8]
Create labels for the project

**Comment by gbrivady** [comment]
Added a bunch of new labels, that I document here.

Priorities for regular workflow (both issues and features):
- **High** : Bottleneck for the development of new features, important bugs to patch, major features that will require a lot of testing...
- **Medium** : Tuned-down version of the above; i.e. important stuff that isn't blocking _yet_, that will require a fair amount of testing, etc...
- **Low** : Everything else that is planned

The idea is to assign people to anything that is available, by priority. The priority is not aimed to be definitive, so if something low is the only thing dont fixed/dev'd for the next milestone, it should be bumped to Medium/High priority.

Other labels:
- **Priority : Critical**: **iff** we need to push a patch very fast, intended to be used outside of regular workflow. For example if we discover a very severe bug right after releasing a version. Mostly there _just in case_.
- **Not planned**: self-explanatory. See it like a "weak" version of the `wontfix` label.

**Comment by amtoine** [comment]
these issues look fine to me :+1:

maybe even a lot of them given the size of the project and its dev team for now, but these labels could prove usefull later in the development process
